services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474" # HTTP port
      - "7687:7687" # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/conf:/conf
    profiles:
      - local
      - prod
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  wikipedia_graph:
    build:
      context: ..
      dockerfile: env/wikipedia_graph/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - neo4j
    environment:
      - WIKIPEDIA_REQUEST_TIMEOUT=50
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_POOL_SIZE=15
      - NEO4J_POOL_OVERFLOW=5
    profiles:
      - prod
